service: snowflake-tokenizer
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-2
  environment:
    REGION: us-east-2
    SECRET_NAME: skyflow-snowflake-vault-credentials
    SECRET_KEY: raw-credential
    VAULT_URI: https://ebfc9bee4242.vault.skyflowapis.com/v1/vaults/o488f35c10e5415cb123fb3d2a16560b
    VAULT_ID: o488f35c10e5415cb123fb3d2a16560b